### ISSUE TITLE
Add better color on selected text in dark mode 

### ISSUE THREAD

**Issue by itsjzt** [thepracticaldev/dev.to#2799]
The text in dark mode looks great but selected text looks ugly

It would be great if we can add a different color on selected text using `::selection` pseudo element.

**Additional context**
![Screenshot_20190512-134014_Chrome](https://user-images.githubusercontent.com/22629916/57579628-8b39b780-74bc-11e9-8409-7115206dea61.jpg)

**Comment by mariocsee** [comment]
If anyone wants to tackle this, it seems like it might be an issue specific to the Android app. Below are screenshots of me using night theme in the iOS app and on Chrome.

![IMG_0841](https://user-images.githubusercontent.com/13403332/57869384-ecba9880-77d2-11e9-86fc-9b4e139c984a.jpeg)
![2019-05-16 12 02 35](https://user-images.githubusercontent.com/13403332/57869391-f2b07980-77d2-11e9-8fd9-d9be44040413.gif)

**Comment by itsjzt** [comment]
Oh, are you going to fix it, in our site

**Comment by Antonio-Cabrero** [comment]
Has this been done? I'd like to take a dive into it :)

**Comment by rhymes** [comment]
@Antonio-Cabrero no, I believe this is still an open issue, you can dive into it :)

**Comment by Ritwik880** [comment]
Hey @rhymes, @jessleenyc Is this issue is solved, if not then i want to fix this issue.

**Comment by rhymes** [comment]
No, it isn't. I'll assign you to the issue

**Comment by supercodingninja** [comment]
code {
    -webkit-user-select: all;
    user-select: all;
};
    
code:focus {
    animation: select 100ms step-end forwards;
};
    
@Keyframes select {
    to {
    -webkit-user-select: text;
    user-select: text;
    }
};

**Comment by supercodingninja** [comment]
Awesome idea, @Ritwik880; however, I believe your code should be written like this:

`code {
    -webkit-user-select: all;
    user-select: all;
};
    
code:focus {
    animation: select 100ms step-end forwards;
};
    
@Keyframes select {
    to {
    -webkit-user-select: text;
    user-select: text;
    }
};`

I hope this helps.

**Comment by cmgorton** [comment]
Hey @Ritwik880 👋 wanted to check in and see if is this an issue you are still working on.

**Comment by Dev-Akash** [comment]
Hi, it seems that this issue still needs some work. Can I work on it, but i would need guidance.

**Comment by cmgorton** [comment]
> Hi @cmgorton , it seems that this issue still needs some work. Can I work on it, but i would need guidance.

Hey @Dev-Akash ! Yes I will assign this to you to work on. Thank you for your help here. Please feel free to ask any questions here as you get started and we will try to help guide you.

**Comment by Dev-Akash** [comment]
Thanks @cmgorton for the opportunity, i will do the needful asap.

**Comment by rafaVls** [comment]
Hi! Is this issue still available? I'd like to claim it for the bug smash.

**Comment by Farhaduneci** [comment]
> Hi! Is this issue still available? I'd like to claim it for the bug smash.

Well, it has been assigned to @Dev-Akash 5 days ago. He must be working on it. if not, I would like to have a chance for solving this one @cmgorton please :D

**Comment by Dev-Akash** [comment]
Hi, @Farhaduneci yeah currently I am working on it.

**Comment by cmgorton** [comment]
@rafaVls @Farhaduneci Thanks for your willingness to help. @Dev-Akash is working on this one but since we have had a pretty good response with the bug smash event I will be adding a few more bugs to the bug smash label today. Check back later today and if you see one you would like to work on please let me know!

**Comment by Dev-Akash** [comment]
Hi @cmgorton, i was setting up the forem using command `bin/setup` but encountering a issue of `ConnectionNotEstablished: fe_sendauth: no password supplied` while preparing for the database. How can i fix this issue ?
I have gone through the [Preparing the Database](https://docs.forem.com/getting-started/db/) but didn't found the solution for this.

**Comment by rhymes** [comment]
Hi @Dev-Akash, you might have a to supply a password to your database connection.

In your `.env` you should add/change `DATABASE_URL` to something like: `postgresql://USERNAME:PASSWORD@HOSTNAME/Forem_development` and then re-run `bin/setup`

**Comment by Link2Twenty** [comment]
@rhymes maybe we should make a bash `.env` builder, asks a bunch of questions (with default answers if left blank) spits out a file.

**Comment by rhymes** [comment]
@Link2Twenty I wonder if documentation wouldn't be more effective

**Comment by Dev-Akash** [comment]
> Hi @Dev-Akash, you might have a to supply a password to your database connection.
> 
> In your `.env` you should add/change `DATABASE_URL` to something like: `postgresql://USERNAME:PASSWORD@HOSTNAME/Forem_development` and then re-run `bin/setup`

I would say that as mentioned in [installing docs](https://docs.forem.com/installation/linux/) for Postgres, it didn't asked for the `PASSWORD`, so it was hard to know what to replace with in above `DATABASE_URL`, Later on I came to know that default `USERNAME` for Postgres after the installation is `postgres` and `HOSTNAME` is `localhost` and then by reading from [this article](https://chartio.com/resources/tutorials/how-to-set-the-default-user-password-in-postgresql/) I managed to setup password for the default `username`.
With which finally landed up with this url:
`postgresql://postgres:root@localhost/$DATABASE_NAME`
and it worked.

So, i think it would be great if this information of default `HOSTNAME`, `USERNAME` and how to set password to pass it later on in the `DATABASE_URL` would be added as a note in the installation docs for linux.

**Comment by Dev-Akash** [comment]
I again encountered an issue during `bin/setup`,

== Bust Caches ==
rails aborted!
Brpoplpush::RedisScript::LuaError: @user_script: 94: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

    92: if not prev_jid or prev_jid == false then
    93:   log_debug("SET", digest, job_id)
    => 94:   redis.call("SET", digest, job_id)
    95: elseif prev_jid == job_id then
    96:   log_debug(digest, "already queued with job_id:", job_id)

how can i fix this ?

**Comment by Link2Twenty** [comment]
Maybe we should update this to something like.

https://github.com/forem/forem/blob/de488f331d493f84bcafd187d121efc2af837f27/.env_sample#L46-L47

```env
# Replace [DB_USERNAME] and [DB_PASSWORD] with your postgres user details
DATABASE_URL="postgresql://[DB_USERNAME]:[DB_PASSWORD]@localhost:5432/Forem_development" 
````

**Comment by rhymes** [comment]
@Dev-Akash looks like a problem of your Redis installation. How have you installed it? Can you restart it?

@Link2Twenty that sounds like a plan, maybe combined with a clearer messaging in the installation docs about telling people they have to customize that URL and not take it verbatim! But we can have this discussion around a specific issue ticket I guess

**Comment by Dev-Akash** [comment]
> @Dev-Akash looks like a problem of your Redis installation. How have you installed it? Can you restart it?
> 
> @Link2Twenty that sounds like a plan, maybe combined with a clearer messaging in the installation docs about telling people they have to customize that URL and not take it verbatim! But we can have this discussion around a specific issue ticket I guess

@rhymes yes i have installed it, i resolved the problem by manually starting the Redis.

Later on i tried to start the application after running `bin/setup` successfully using `bin/startup` and it ended up failing,

Here is the log:

== STARTING UP ==
20:18:29 web.1       | started with pid 3568
20:18:29 webpacker.1 | started with pid 3569
20:18:29 sidekiq.1   | started with pid 3570
20:18:43 sidekiq.1   | 2021-05-07T14:48:43.362Z pid=3570 tid=9gi WARN: ArgumentError: invalid value for Integer(): "5 # Specifies the number of Puma threads"
20:18:43 sidekiq.1   | 2021-05-07T14:48:43.363Z pid=3570 tid=9gi WARN: /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:246:in `Integer'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:246:in `setup_options'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:24:in `parse'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sidekiq-6.2.1/bin/sidekiq:27:in `<top (required)>'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/bin/sidekiq:23:in `load'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/bin/sidekiq:23:in `<top (required)>'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
20:18:43 sidekiq.1   | /home/dev-akash/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
20:18:43 sidekiq.1   | exited with code 1
20:18:43 system      | sending SIGTERM to all processes
20:18:43 web.1       | terminated by SIGTERM
20:18:44 webpacker.1 | terminated by SIGTERM

== Command ["foreman start -f Procfile.dev"] failed ==

**Comment by Link2Twenty** [comment]
@Dev-Akash [.env-sample](https://github.com/forem/forem/blob/main/.env_sample) has been updated to fix this problem, can you compare your `.env` to it and bring it up to date

**Comment by Dev-Akash** [comment]
Thanks @Link2Twenty, it solved the issue, re-run the `bin/setup` and `bin/startup` and opened `localhost:3000` it shows the following message.

![Screenshot from 2021-05-07 21-21-53](https://user-images.githubusercontent.com/43779954/117476018-5745df80-af7a-11eb-9f31-46eba59b4d28.png)

**Comment by Dev-Akash** [comment]
> @Dev-Akash have you tried to restart Redis?

Yes i did @rhymes

**Comment by rhymes** [comment]
@Link2Twenty you get me :D

**Comment by Dev-Akash** [comment]
@rhymes do i need to use [these](https://docs.forem.com/getting-started/db/#default-admin-user) credentials to log in as mentioned under default-admin-user section, as it is not working for me.

**Comment by rhymes** [comment]
@Dev-Akash what is it saying?

**Comment by Dev-Akash** [comment]
> @Dev-Akash what is it saying?

Invalid email or password.

![Screenshot from 2021-05-07 23-02-38](https://user-images.githubusercontent.com/43779954/117487169-587e0900-af88-11eb-9743-d6a9bb186e45.png)

**Comment by rhymes** [comment]
@Dev-Akash mmm weird, you can change the admin's password from the console if you need to:

```ruby
> bundle exec rails console
admin = User.find_by(email: "admin@forem.local")
admin.update(password: NEW_PASSWORD, password_confirmation: NEW_PASSWORD)
```

**Comment by cmgorton** [comment]
Hey @Dev-Akash wanted to check in and see how you are doing with this issue. Did you have any questions or need any help?

**Comment by rt4914** [comment]
Considering there has been no progress on this issue. I am assigning this to myself.

**Comment by rt4914** [comment]
Un-assigning myself for now. If someone else ends up working on this, have a look at this [comment](https://github.com/forem/forem/pull/14343#issuecomment-892648199) which summarises the next steps for this project. Thanks.

**Comment by akshatcoder-hash** [comment]
Hey @rt4914 could you please assign this issue to me? I would love to work on it

**Comment by MustkimKhatik** [comment]
Anybody working on it?!

**Comment by twhite96** [comment]
Hey team. I'm willing to take a gander at this. I have the repo setup in Gitpod and am ready to go. I'll need to configure environment variables and whatnot, but that will have to wait till morning as it is almost 1:30 AM here. 😅

**Comment by shahilpatel-3602** [comment]
I would like to work on this issue, please assign me this this if it is not solved already.

**Comment by KSSaiTeja** [comment]
if the issue open, i will work upon it, fix the bug. But as beginner i need some help that how can i reproduce the bug and fix it

**Comment by chiragthakur09** [comment]
I would like to work on this issue, feel free to assign me.

**Comment by mirie** [comment]
@chiragthakur09 Awesome! I will assign it to you. Thanks for taking on this long running issue 🙇‍♀️

**Comment by KSSaiTeja** [comment]
@mrmir i asked to assign this issue so long ago.. could you please assign this to me..

**Comment by KSSaiTeja** [comment]
@mirie

**Comment by KSSaiTeja** [comment]
@mirie i have raised a PR and inserted images also.. please review them and merge my PR. it will be more motivational to me.

**Comment by mirie** [comment]
@KSSaiTeja sorry I missed your message! I have updated the assignment -- thanks so much for your ping 🙇‍♀️

**Comment by KSSaiTeja** [comment]
yeah.. please review my PR. and hope you will merge my PR.

**Comment by luciagirasoles** [comment]
Hi, FYI I use https://www.genymotion.com/ for virtual android devices. I also could replicate the issue there.

**Comment by akhil0203** [comment]
@mirie I would love to work on this issue if it is still open please feel free to assign me.

**Comment by ir3ne** [comment]
@KSSaiTeja I see you've already open a PR for this and I see some comments on that, do you need some help?

**Comment by KSSaiTeja** [comment]
i fixed the issue but i don't know why it's not being merged

**Comment by ir3ne** [comment]
@KSSaiTeja I see not all the checks pass.

![Screenshot 2024-03-26 at 10 20 30](https://github.com/forem/forem/assets/23403047/19a5b156-f286-4789-b628-8ae3145f97ed)

**Comment by KARUNANS2004** [comment]
Hi @rhymes , @jessleenyc  , Is this issue solved, If not then I want to fix the issue

**Comment by Link2Twenty** [comment]
@KARUNANS2004 the issue is already solved in a PR await merger.

**Comment by extinctsion** [comment]
Is this even fixed or not?

**Comment by Venkatesh2507** [comment]
Hello 
Is this issue closed or anyone working on it??

**Comment by mikeydorje** [comment]
Closing as low‑priority/stale. There are open PRs (#22100, #22130) that attempted to address this but weren’t merged. If this is still desired, please open a fresh issue (or revive one of those PRs) with current screenshots and acceptance criteria.
