### ISSUE TITLE
Help me to setup this project on aws or heroku

### ISSUE THREAD

**Issue by ozzzzam** [thepracticaldev/dev.to#453]
This error on Heroku

 /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by ozzzzam** [comment]
Thanks for reply,

here is the full error

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.5.1
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rails-assets.org/..
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rails-assets.org/..
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rails-assets.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching https://github.com/thepracticaldev/acts_as_follower.git
       Fetching https://github.com/bufferapp/buffer-ruby.git
       Fetching gem metadata from https://rails-assets.org/..
       Fetching version metadata from https://rails-assets.org/.
       Fetching rake 12.3.1
       Fetching CFPropertyList 2.3.6
       Fetching concurrent-ruby 1.0.5
       Installing CFPropertyList 2.3.6
       Installing rake 12.3.1
       Installing concurrent-ruby 1.0.5
       Fetching minitest 5.11.3
       Installing minitest 5.11.3
       Fetching thread_safe 0.3.6
       Installing thread_safe 0.3.6
       Fetching builder 3.2.3
       Installing builder 3.2.3
       Fetching erubi 1.7.1
       Installing erubi 1.7.1
       Fetching mini_portile2 2.3.0
       Installing mini_portile2 2.3.0
       Fetching crass 1.0.4
       Installing crass 1.0.4
       Fetching rack 2.0.5
       Fetching nio4r 2.3.1
       Installing nio4r 2.3.1 with native extensions
       Installing rack 2.0.5
       Fetching websocket-extensions 0.1.3
       Installing websocket-extensions 0.1.3
       Fetching mini_mime 1.0.0
       Installing mini_mime 1.0.0
       Fetching arel 8.0.0
       Installing arel 8.0.0
       Fetching public_suffix 3.0.2
       Installing public_suffix 3.0.2
       Fetching execjs 2.7.0
       Installing execjs 2.7.0
       Fetching method_source 0.9.0
       Fetching thor 0.20.0
       Installing method_source 0.9.0
       Installing thor 0.20.0
       Fetching kaminari-core 1.1.1
       Installing kaminari-core 1.1.1
       Fetching rb-fsevent 0.10.2
       Fetching ffi 1.9.25
       Installing rb-fsevent 0.10.2
       Fetching tilt 2.0.8
       Installing tilt 2.0.8
       Installing ffi 1.9.25 with native extensions
       Fetching selectize-rails 0.12.4.1
       Installing selectize-rails 0.12.4.1
       Using bundler 1.15.2
       Fetching errbase 0.0.3
       Installing errbase 0.0.3
       Fetching airbrake-ruby 1.8.0
       Installing airbrake-ruby 1.8.0
       Fetching httpclient 2.8.3
       Installing httpclient 2.8.3
       Fetching json 1.8.6
       Installing json 1.8.6 with native extensions
       Fetching multi_xml 0.6.0
       Installing multi_xml 0.6.0
       Fetching aws-partitions 1.82.0
       Installing aws-partitions 1.82.0
       Fetching aws-sigv4 1.0.2
       Installing aws-sigv4 1.0.2
       Fetching jmespath 1.4.0
       Installing jmespath 1.4.0
       Fetching aws_cf_signer 0.1.3
       Installing aws_cf_signer 0.1.3
       Fetching ice_nine 0.11.2
       Installing ice_nine 0.11.2
       Fetching babel-source 5.8.35
       Installing babel-source 5.8.35
       Fetching bcrypt 3.1.11
       Installing bcrypt 3.1.11 with native extensions
       Fetching environs 1.1.0
       Installing environs 1.1.0
       Fetching multipart-post 2.0.0
       Installing multipart-post 2.0.0
       Fetching hashie 3.5.7
       Installing hashie 3.5.7
       Fetching multi_json 1.13.1
       Installing multi_json 1.13.1
       Fetching yajl-ruby 1.4.0
       Installing yajl-ruby 1.4.0 with native extensions
       Fetching buftok 0.2.0
       Installing buftok 0.2.0
       Fetching mime-types-data 3.2016.0521
       Installing mime-types-data 3.2016.0521
       Fetching fastimage 2.1.1
       Installing fastimage 2.1.1
       Fetching unf_ext 0.0.7.5
       Installing unf_ext 0.0.7.5 with native extensions
       Fetching netrc 0.11.0
       Installing netrc 0.11.0
       Fetching coderay 1.1.2
       Installing coderay 1.1.2
       Fetching coffee-script-source 1.12.2
       Installing coffee-script-source 1.12.2
       Fetching dalli 2.7.6
       Installing dalli 2.7.6
       Fetching declarative 0.0.10
       Installing declarative 0.0.10
       Fetching declarative-option 0.1.0
       Installing declarative-option 0.1.0
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching equalizer 0.0.11
       Installing equalizer 0.0.11
       Fetching excon 0.60.0
       Installing excon 0.60.0
       Fetching fastly 1.13.2
       Installing fastly 1.13.2
       Fetching sax-machine 1.3.2
       Installing sax-machine 1.3.2
       Fetching formatador 0.2.5
       Installing formatador 0.2.5
       Fetching ipaddress 0.8.3
       Installing ipaddress 0.8.3
       Fetching xml-simple 1.1.5
       Installing xml-simple 1.1.5
       Fetching inflecto 0.0.2
       Installing inflecto 0.0.2
       Fetching trollop 2.1.2
       Installing trollop 2.1.2
       Fetching front_matter_parser 0.1.1
       Installing front_matter_parser 0.1.1
       Fetching get_process_mem 0.2.2
       Installing get_process_mem 0.2.2
       Fetching jwt 1.5.6
       Installing jwt 1.5.6
       Fetching little-plugger 1.1.4
       Installing little-plugger 1.1.4
       Fetching memoist 0.16.0
       Installing memoist 0.16.0
       Fetching os 0.9.6
       Installing os 0.9.6
       Fetching uber 0.1.0
       Installing uber 0.1.0
       Fetching retriable 3.1.1
       Installing retriable 3.1.1
       Fetching hkdf 0.3.0
       Installing hkdf 0.3.0
       Fetching http-form_data 2.0.0
       Installing http-form_data 2.0.0
       Fetching http_parser.rb 0.6.0
       Installing http_parser.rb 0.6.0 with native extensions
       Fetching http_signatures 0.2.2
       Installing http_signatures 0.2.2
       Fetching libv8 3.16.14.19 (x86_64-linux)
       Fetching liquid 4.0.0
       Installing liquid 4.0.0
       Installing libv8 3.16.14.19 (x86_64-linux)
       Fetching msgpack 1.2.4
       Installing msgpack 1.2.4 with native extensions
       Fetching nakayoshi_fork 0.0.4
       Installing nakayoshi_fork 0.0.4
       Fetching naught 1.1.0
       Installing naught 1.1.0
       Fetching oauth 0.5.4
       Installing oauth 0.5.4
       Fetching pg 1.0.0
       Installing pg 1.0.0 with native extensions
       Fetching puma 3.11.2
       Installing puma 3.11.2 with native extensions
       Fetching pusher-signature 0.1.8
       Installing pusher-signature 0.1.8
       Fetching rack-timeout 0.5.1
       Installing rack-timeout 0.5.1
       Fetching rails-assets-airbrake-js-client 0.9.8
       Installing rails-assets-airbrake-js-client 0.9.8
       Fetching rdoc 4.3.0
       Installing rdoc 4.3.0
       Fetching redcarpet 3.4.0
       Installing redcarpet 3.4.0 with native extensions
       Fetching ref 2.0.0
       Installing ref 2.0.0
       Fetching rolify 5.2.0
       Installing rolify 5.2.0
       Fetching rouge 3.1.1
       Installing rouge 3.1.1
       Fetching share_meow_client 0.1.3
       Installing share_meow_client 0.1.3
       Fetching simple_oauth 0.3.1
       Installing simple_oauth 0.3.1
       Fetching slack-notifier 1.5.1
       Installing slack-notifier 1.5.1
       Fetching staccato 0.5.1
       Installing staccato 0.5.1
       Fetching fission 0.5.0
       Installing fission 0.5.0
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching descendants_tracker 0.0.4
       Installing descendants_tracker 0.0.4
       Fetching memoizable 0.4.2
       Installing memoizable 0.4.2
       Fetching i18n 1.0.1
       Installing i18n 1.0.1
       Fetching nokogiri 1.8.4
       Installing nokogiri 1.8.4 with native extensions
       Fetching websocket-driver 0.6.5
       Installing websocket-driver 0.6.5 with native extensions
       Fetching mail 2.7.0
       Installing mail 2.7.0
       Fetching rack-test 1.0.0
       Installing rack-test 1.0.0
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching warden 1.2.7
       Installing warden 1.2.7
       Fetching request_store 1.4.0
       Fetching rack-host-redirect 1.3.0
       Installing rack-host-redirect 1.3.0
       Installing request_store 1.4.0
       Fetching rack-proxy 0.6.4
       Fetching autoprefixer-rails 6.7.7.2
       Installing rack-proxy 0.6.4
       Fetching uglifier 3.2.0
       Installing autoprefixer-rails 6.7.7.2
       Installing uglifier 3.2.0
       Fetching addressable 2.5.2
       Installing addressable 2.5.2
       Fetching figaro 1.1.1
       Installing figaro 1.1.1
       Fetching safely_block 0.2.0
       Installing safely_block 0.2.0
       Fetching airbrake 5.8.1
       Installing airbrake 5.8.1
       Fetching httparty 0.16.0
       Installing httparty 0.16.0
       Fetching aws-sdk-core 3.20.2
       Installing aws-sdk-core 3.20.2
       Fetching babel-transpiler 0.7.0
       Installing babel-transpiler 0.7.0
       Fetching rb-inotify 0.9.10
       Installing rb-inotify 0.9.10
       Fetching faraday 0.12.2
       Installing faraday 0.12.2
       Fetching omniauth 1.8.1
       Installing omniauth 1.8.1
       Fetching keen 0.7.8
       Fetching mime-types 3.1
       Installing keen 0.7.8
       Installing mime-types 3.1
       Fetching pry 0.11.3
       Fetching coffee-script 2.4.1
       Installing pry 0.11.3
       Installing coffee-script 2.4.1
       Fetching fog-core 1.45.0
       Installing fog-core 1.45.0
       Fetching logging 2.2.2
       Fetching representable 3.0.4
       Installing logging 2.2.2
       Installing representable 3.0.4
       Fetching webpush 0.3.2
       Installing webpush 0.3.2
       Fetching unf 0.1.4
       Fetching algoliasearch 1.19.1
       Installing unf 0.1.4
       Installing algoliasearch 1.19.1
       Fetching recaptcha 4.6.4
       Installing recaptcha 4.6.4
       Fetching timber 2.6.1
       Fetching pusher 1.3.1
       Installing timber 2.6.1
       Installing pusher 1.3.1
       Fetching sdoc 0.4.2
       Installing sdoc 0.4.2
       Fetching therubyracer 0.12.3
       Fetching axiom-types 0.1.1
       Installing therubyracer 0.12.3 with native extensions
       Installing axiom-types 0.1.1
       Fetching coercible 1.0.0
       Installing coercible 1.0.0
       Fetching activesupport 5.1.6
       Installing activesupport 5.1.6
       Fetching puma_worker_killer 0.1.0
       Installing puma_worker_killer 0.1.0
       Fetching algorithmia 1.0.1
       Installing algorithmia 1.0.1
       Fetching sprockets-es6 0.9.2
       Installing sprockets-es6 0.9.2
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching faraday_middleware 0.12.2
       Installing faraday_middleware 0.12.2
       Fetching gibbon 2.2.5
       Installing gibbon 2.2.5
       Fetching signet 0.8.1
       Installing signet 0.8.1
       Fetching oauth2 1.4.0
       Installing oauth2 1.4.0
       Fetching sawyer 0.8.1
       Installing sawyer 0.8.1
       Fetching stream-ruby 2.5.10
       Installing stream-ruby 2.5.10
       Fetching stripe 3.15.0
       Installing stripe 3.15.0
       Fetching aws-sdk-lambda 1.5.0
       Installing aws-sdk-lambda 1.5.0
       Fetching omniauth-oauth 1.1.0
       Installing omniauth-oauth 1.1.0
       Fetching fog-json 1.0.2
       Installing fog-json 1.0.2
       Fetching fog-local 0.4.0
       Installing fog-local 0.4.0
       Fetching fog-vmfusion 0.1.0
       Installing fog-vmfusion 0.1.0
       Fetching pry-rails 0.3.6
       Installing pry-rails 0.3.6
       Fetching domain_name 0.5.20170404
       Installing domain_name 0.5.20170404
       Fetching algoliasearch-rails 1.20.4
       Installing algoliasearch-rails 1.20.4
       Fetching envied 0.9.1
       Installing envied 0.9.1
       Fetching virtus 1.0.5
       Installing virtus 1.0.5
       Fetching globalid 0.4.1
       Installing globalid 0.4.1
       Fetching activemodel 5.1.6
       Installing activemodel 5.1.6
       Fetching csv_shaper 1.3.0
       Installing csv_shaper 1.3.0
       Fetching delayed_job 4.1.4
       Installing delayed_job 4.1.4
       Fetching flipflop 2.3.1
       Installing flipflop 2.3.1
       Fetching jbuilder 2.7.0
       Installing jbuilder 2.7.0
       Fetching pundit 1.1.0
       Installing pundit 1.1.0
       Fetching skylight 1.5.1
       Installing skylight 1.5.1 with native extensions
       Fetching sass 3.5.5
       Installing sass 3.5.5
       Using buffer 0.1.2 from https://github.com/bufferapp/buffer-ruby.git (at master@10edfe6)
       Fetching googleauth 0.6.2
       Installing googleauth 0.6.2
       Fetching omniauth-oauth2 1.5.0
       Installing omniauth-oauth2 1.5.0
       Fetching octokit 4.8.0
       Installing octokit 4.8.0
       Fetching omniauth-twitter 1.4.0
       Installing omniauth-twitter 1.4.0
       Fetching fog-aliyun 0.2.0
       Installing fog-aliyun 0.2.0
       Fetching fog-brightbox 0.14.0
       Installing fog-brightbox 0.14.0
       Fetching fog-dnsimple 1.0.0
       Installing fog-dnsimple 1.0.0
       Fetching fog-joyent 0.0.1
       Installing fog-joyent 0.0.1
       Fetching fog-openstack 0.1.24
       Installing fog-openstack 0.1.24
       Fetching fog-profitbricks 4.1.1
       Fetching fog-sakuracloud 1.7.5
       Installing fog-profitbricks 4.1.1
       Installing fog-sakuracloud 1.7.5
       Fetching fog-serverlove 0.1.2
       Installing fog-serverlove 0.1.2
       Fetching fog-softlayer 1.1.4
       Installing fog-softlayer 1.1.4
       Fetching fog-storm_on_demand 0.1.1
       Installing fog-storm_on_demand 0.1.1
       Fetching http-cookie 1.0.3
       Installing http-cookie 1.0.3
       Fetching activejob 5.1.6
       Fetching activerecord 5.1.6
       Installing activejob 5.1.6
       Installing activerecord 5.1.6
       Fetching activemodel-serializers-xml 1.0.2
       Installing activemodel-serializers-xml 1.0.2
       Fetching carrierwave 1.2.2
       Fetching email_validator 1.6.0
       Installing email_validator 1.6.0
       Installing carrierwave 1.2.2
       Fetching rails-observers 0.1.5
       Installing rails-observers 0.1.5
       Fetching validate_url 1.0.2
       Fetching rails-dom-testing 2.0.3
       Installing validate_url 1.0.2
       Installing rails-dom-testing 2.0.3
       Fetching loofah 2.2.2
       Installing loofah 2.2.2
       Fetching fog-xml 0.1.3
       Installing fog-xml 0.1.3
       Fetching rbvmomi 1.11.6
       Fetching html_truncator 0.4.2
       Installing html_truncator 0.4.2
       Installing rbvmomi 1.11.6
       Fetching reverse_markdown 1.0.5
       Installing reverse_markdown 1.0.5
       Fetching twilio-ruby 5.10.3
       Fetching bourbon 1.4.0
       Installing bourbon 1.4.0
       Installing twilio-ruby 5.10.3
       Fetching google-api-client 0.19.8
       Fetching omniauth-github 1.3.0
       Installing omniauth-github 1.3.0
       Fetching rest-client 2.0.2
       Installing rest-client 2.0.2
       Fetching http 3.0.0
       Installing google-api-client 0.19.8
       Installing http 3.0.0
       Fetching carrierwave-bombshelter 0.2.2
       Installing carrierwave-bombshelter 0.2.2
       Fetching fog-atmos 0.1.0
       Installing fog-atmos 0.1.0
       Fetching fog-aws 2.0.0
       Installing fog-aws 2.0.0
       Fetching fog-cloudatcost 0.1.2
       Installing fog-cloudatcost 0.1.2
       Fetching fog-digitalocean 0.3.0
       Installing fog-digitalocean 0.3.0
       Fetching fog-dynect 0.0.3
       Installing fog-dynect 0.0.3
       Fetching fog-ecloud 0.3.0
       Installing fog-ecloud 0.3.0
       Fetching fog-google 0.1.0
       Installing fog-google 0.1.0
       Fetching fog-internet-archive 0.0.1
       Installing fog-internet-archive 0.0.1
       Fetching fog-powerdns 0.1.1
       Installing fog-powerdns 0.1.1
       Fetching fog-rackspace 0.1.5
       Installing fog-rackspace 0.1.5
       Fetching fog-radosgw 0.0.5
       Installing fog-radosgw 0.0.5
       Fetching fog-riakcs 0.1.0
       Installing fog-riakcs 0.1.0
       Fetching fog-terremark 0.1.0
       Installing fog-terremark 0.1.0
       Fetching fog-voxel 0.1.0
       Installing fog-voxel 0.1.0
       Fetching fog-xenserver 0.3.0
       Installing fog-xenserver 0.3.0
       Fetching rails-html-sanitizer 1.0.4
       Installing rails-html-sanitizer 1.0.4
       Fetching feedjira 2.1.4
       Installing feedjira 2.1.4
       Fetching inline_svg 0.12.1
       Installing inline_svg 0.12.1
       Fetching fog-vsphere 1.13.1
       Installing fog-vsphere 1.13.1
       Fetching active_record_union 1.3.0
       Installing active_record_union 1.3.0
       Fetching acts-as-taggable-on 5.0.0
       Installing acts-as-taggable-on 5.0.0
       Using acts_as_follower 0.2.1 from https://github.com/thepracticaldev/acts_as_follower.git (at master@288690c)
       Fetching kaminari-activerecord 1.1.1
       Installing kaminari-activerecord 1.1.1
       Fetching after_commit_action 1.1.0
       Installing after_commit_action 1.1.0
       Fetching ancestry 3.0.1
       Installing ancestry 3.0.1
       Fetching delayed_job_active_record 4.1.2
       Installing delayed_job_active_record 4.1.2
       Fetching cloudinary 1.9.1
       Installing cloudinary 1.9.1
       Fetching twitter 6.2.0
       Installing twitter 6.2.0
       Fetching actionview 5.1.6
       Fetching counter_culture 1.9.0
       Installing counter_culture 1.9.0
       Installing actionview 5.1.6
       Fetching fog 1.41.0
       Installing fog 1.41.0
       Fetching actionpack 5.1.6
       Fetching kaminari-actionview 1.1.1
       Installing kaminari-actionview 1.1.1
       Installing actionpack 5.1.6
       Fetching kaminari 1.1.1
       Installing kaminari 1.1.1
       Fetching actioncable 5.1.6
       Fetching actionmailer 5.1.6
       Installing actioncable 5.1.6
       Installing actionmailer 5.1.6
       Fetching actionpack-action_caching 1.2.0
       Installing actionpack-action_caching 1.2.0
       Fetching railties 5.1.6
       Fetching sprockets-rails 3.2.1
       Installing railties 5.1.6
       Installing sprockets-rails 3.2.1
       Fetching draper 3.0.1
       Installing draper 3.0.1
       Fetching momentjs-rails 2.17.1
       Fetching jquery-rails 4.3.1
       Installing momentjs-rails 2.17.1
       Installing jquery-rails 4.3.1
       Fetching sass-rails 5.0.7
       Installing sass-rails 5.0.7
       Fetching rails 5.1.6
       Installing rails 5.1.6
       Fetching coffee-rails 4.2.2
       Installing coffee-rails 4.2.2
       Fetching responders 2.4.0
       Installing responders 2.4.0
       Fetching fastly-rails 0.8.0
       Installing fastly-rails 0.8.0
       Fetching jquery-fileupload-rails 0.4.7
       Installing jquery-fileupload-rails 0.4.7
       Fetching serviceworker-rails 0.5.5
       Installing serviceworker-rails 0.5.5
       Fetching stream_rails 2.5.2
       Installing stream_rails 2.5.2
       Fetching webpacker 3.5.3
       Installing webpacker 3.5.3
       Fetching ahoy_email 0.5.0
       Installing ahoy_email 0.5.0
       Fetching storext 2.2.2
       Installing storext 2.2.2
       Fetching devise 4.4.1
       Installing devise 4.4.1
       Fetching datetime_picker_rails 0.0.7
       Installing datetime_picker_rails 0.0.7
       Fetching s3_direct_upload 0.1.7
       Installing s3_direct_upload 0.1.7
       Fetching administrate 0.9.0
       Installing administrate 0.9.0
       Bundle complete! 127 Gemfile dependencies, 260 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from acts-as-taggable-on:
       When upgrading
       
       Re-run the migrations generator
       
           rake acts_as_taggable_on_engine:install:migrations
       
       This will create any new migrations and skip existing ones
       Version 3.5.0 has a migration for mysql adapter
       Post-install message from httparty:
       When you HTTParty, you must party hard!
       Post-install message from fog:
       ------------------------------
       Thank you for installing fog!
       
       IMPORTANT NOTICE:
       If there's a metagem available for your cloud provider, e.g. `fog-aws`,
       you should be using it instead of requiring the full fog collection to avoid
       unnecessary dependencies.
       
       'fog' should be required explicitly only if:
       - The provider you use doesn't yet have a metagem available.
       - You require Ruby 1.9.3 support.
       ------------------------------
       Bundle completed (88.43s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       The latest bundler is 1.16.3, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Installing node-v8.10.0-linux-x64
-----> Installing yarn-v1.5.1
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       ArgumentError: The api_key parameter cannot be blank
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/timber-2.6.1/lib/timber/log_devices/http.rb:71:in `initialize'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/config/environments/production.rb:95:in `new'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/config/environments/production.rb:95:in `block in <top (required)>'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:211:in `instance_eval'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/railtie.rb:211:in `configure'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/config/environments/production.rb:3:in `<top (required)>'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:599:in `each'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:599:in `block in <class:Engine>'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/config/environment.rb:5:in `<top (required)>'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
       /tmp/build_05bd55160ee432cd13e79d65af8382b5/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by rhymes** [comment]
Before the actual traceback you can find the error message:

> ArgumentError: The api_key parameter cannot be blank

The first few lines of the error should give you a clue. It says the error comes from line 95 of [production.rb](https://github.com/thepracticaldev/dev.to/blob/master/config/environments/production.rb#L95)

Since you're trying to deploy the app on a production environment you need to get all the keys the app needs. In this case you need a [Timber](https://timber.io/) api key and you need to set it as an environment variable like you see at line 95.

**Comment by ozzzzam** [comment]
Ok Thanks, I will try, Actually I'm trying to setup development ENV

**Comment by benhalpern** [comment]
@ozzzzam can you clarify what the bigger picture of what you're doing in terms of deployment right now? There are several details which make it a little too soon to stand up your own instance on the open web. Happy to work through that with you, but if you could give me an idea of what you're doing, that would be great.

**Comment by pkfrank** [comment]
Hey @ozzzzam, I just wanted to alert you to [this thread](https://dev.to/ben/so-you-want-to-stand-up-your-own-instance-of-dev-help-thread-1elo) that @benhalpern created yesterday which provides a bit more context that's relevant to eventually setting up your own instance of DEV.

**Comment by maestromac** [comment]
As per @pkfrank, any further discussion is encouraged in that thread.

Closing
