### ISSUE TITLE
Post Article - Encoding::UndefinedConversionError in ArticlesController#create "\xE5" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by incasedo** [thepracticaldev/dev.to#4838]
The tag input box can't include any chinese characters, it got errors  as below when submit article.
````
Encoding::UndefinedConversionError in ArticlesController#create
"\xE5" from ASCII-8BIT to UTF-8
````
Extracted source (around line 38):
````
   if options.is_a?(::JSON::State)
        # Called from JSON.{generate,dump}, forward it to JSON gem's to_json
        super(options)
      else
        # to_json is being invoked directly, use ActiveSupport's encoder
        ActiveSupport::JSON.encode(self, options)
````
Full Trace
````
activesupport (5.2.3) lib/active_support/core_ext/object/json.rb:38:in `encode'
activesupport (5.2.3) lib/active_support/core_ext/object/json.rb:38:in `to_json'
activesupport (5.2.3) lib/active_support/core_ext/object/json.rb:38:in `to_json'
activesupport (5.2.3) lib/active_support/json/encoding.rb:57:in `to_json'
json (2.2.0) lib/json/common.rb:224:in `generate'
json (2.2.0) lib/json/common.rb:224:in `generate'
activesupport (5.2.3) lib/active_support/json/encoding.rb:102:in `stringify'
activesupport (5.2.3) lib/active_support/json/encoding.rb:35:in `encode'
activesupport (5.2.3) lib/active_support/json/encoding.rb:22:in `encode'
````

**Comment by rhymes** [comment]
@incasedo could you kindly paste here an extract of the text you were trying to insert in the editor? It'd be a great help to reproduce the error and investigate it.

Thank you!

**Comment by incasedo** [comment]
it's my own problems, thank you for your reply
