### ISSUE TITLE
Flaky Articles user_visits_an_article_spec

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#4887]
Related to #4884  

The follow spec failed during a CI run of unchanged code in master. 
```
1) Views an article shows comments
     Failure/Error: create_list(:comment, 3, commentable: article)
     
     ActiveRecord::RecordNotFound:
       Couldn't find Article with 'id'=1051
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_views_an_article_shows_comments_7.png
     
     # ./spec/system/articles/user_visits_an_article_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  2) Views an article when showing the date shows the readable publish date
     Failure/Error: article.update_column(:published_at, Time.zone.parse(timestamp))
     
     ActiveRecord::RecordNotFound:
       Couldn't find Article with 'id'=1051
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_views_an_article_when_showing_the_date_shows_the_readable_publish_date_327.png
     
     # ./spec/system/articles/user_visits_an_article_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  3) Views an article when showing the date embeds the published timestamp
     Failure/Error: article.update_column(:published_at, Time.zone.parse(timestamp))
     
     ActiveRecord::RecordNotFound:
       Couldn't find Article with 'id'=1051
     
     
     
     # ./spec/system/articles/user_visits_an_article_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
  
Failed examples:
rspec ./spec/system/articles/user_visits_an_article_spec.rb:17 # Views an article shows comments
rspec ./spec/system/articles/user_visits_an_article_spec.rb:28 # Views an article when showing the date shows the readable publish date
rspec ./spec/system/articles/user_visits_an_article_spec.rb:33 # Views an article when showing the date embeds the published timestamp
```

**Comment by DanP1925** [comment]
I would like to work on this issue if available :)

**Comment by rhymes** [comment]
Hi @DanP1925, sure it's available! and thank you!

I'm going to formally assign you so other contributors will know you're working on it

**Comment by JulianoGTZ** [comment]
Hi. This issue is still available to be fixed?

**Comment by rhymes** [comment]
@JulianoGTZ sure, let us know if you can reproduce it. I'm going to assign you to the issue

**Comment by JulianoGTZ** [comment]
Nice. I will try to reproduce this error.

**Comment by rhymes** [comment]
To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
