### ISSUE TITLE
Flaky user_fills_out_comment_spec Elements Not Found

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#4889]
Related to #4884 

```
  2) Deleting Comment works
     Failure/Error: raise Pundit::NotAuthorizedError, "You must be logged in" unless user
     
     Pundit::NotAuthorizedError:
       You must be logged in
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_deleting_comment_works_829.png
     
     # ./app/policies/application_policy.rb:5:in `initialize'
     # ./app/controllers/comments_controller.rb:131:in `delete_confirm'
     # ------------------
     # --- Caused by: ---
     # Capybara::ElementNotFound:
     #   Unable to find link "DELETE"
     #   ./spec/system/comments/user_delete_a_comment_spec.rb:18:in `block (2 levels) in <top (required)>'
  3) Editing A Comment when user edits comment on the bottom of the article updates
     Failure/Error: click_link("EDIT")
     
     Capybara::ElementNotFound:
       Unable to find visible link "EDIT"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_editing_a_comment_when_user_edits_comment_on_the_bottom_of_the_article_updates_26.png
     
     # ./spec/system/comments/user_edits_a_comment_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  4) Editing A Comment when user edits via permalinks updates
     Failure/Error: click_link("EDIT")
     
     Capybara::ElementNotFound:
       Unable to find visible link "EDIT"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_editing_a_comment_when_user_edits_via_permalinks_updates_356.png
     
     # ./spec/system/comments/user_edits_a_comment_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  5) Creating Comment User fills out comment box normally
     Failure/Error: expect(page).to have_text(raw_comment)
       expected to find text "Voluptas similique sequi. Beatae quo odio. Fugiat suscipit autem." in "App logo\nWRITE A POST\nConnect\nNotifications\n1\nI Sing the Body Electric 833\nEldridge Abshire Nov 22 ・1 min read\n#occupy #pourover #farmtotable #pug\nFixie kale chips viral. Brooklyn occupy tattooed salvia tousled.\nOccupy heirloom ugh fingerstache. Put a bird on it pitchfork selfies slow-carb narwhal ramps small batch. Sriracha selvage crucifix mustache.\n0\n0\n0\nDISCUSS\nPREVIEW\ncode of conduct - report abuse\nEldridge Abshire\n@username3023\nOmnis rerum aliquam. Debitis repellendus quae. Aspernatur vitae quae.\njoined\nNov 22, 2019\nHome About Privacy Policy Terms of Use Contact Code of Conduct\nDEV(local) Community copyright 2016 - 2019  🔥"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_creating_comment_user_fills_out_comment_box_normally_127.png
     
     # ./spec/system/comments/user_fills_out_comment_spec.rb:17:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  6) Creating Comment User fill out commen box then click previews and submit
     Failure/Error: expect(page).to have_text(raw_comment)
       expected to find text "Ea vitae magnam. Dolor ratione laudantium. Dolorem est non." in "App logo\nWRITE A POST\nConnect\nNotifications\n1\nFrom Here to Eternity 220\nJoseph Bogisich Nov 22 ・1 min read\n#selvage #disrupt #ugh #squid\nNeutra park yolo. Pitchfork synth farm-to-table wolf. Five dollar toast occupy tousled narwhal.\nFingerstache fixie twee muggle magic mustache. Cardigan ennui trust fund.\n0\n0\n0\nDISCUSS\nMARKDOWN\ncode of conduct - report abuse\nJoseph Bogisich\n@username3026\nQui quo nam. Harum nam autem. Sed magni illo.\njoined\nNov 22, 2019\nHome About Privacy Policy Terms of Use Contact Code of Conduct\nDEV(local) Community copyright 2016 - 2019  🔥"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_creating_comment_user_fill_out_commen_box_then_click_previews_and_submit_969.png
     
     # ./spec/system/comments/user_fills_out_comment_spec.rb:24:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
  7) Creating Comment User replies to a comment
     Failure/Error: find(:xpath, "//div[@class='actions']/form[@class='new_comment']/textarea").set(raw_comment)
     
     Capybara::ElementNotFound:
       Unable to find xpath "//div[@class='actions']/form[@class='new_comment']/textarea"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_creating_comment_user_replies_to_a_comment_66.png
     
     # ./spec/system/comments/user_fills_out_comment_spec.rb:36:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'

Failed examples:
rspec ./spec/system/comments/user_edits_a_comment_spec.rb:22 # Editing A Comment when user edits comment on the bottom of the article updates
rspec ./spec/system/comments/user_edits_a_comment_spec.rb:30 # Editing A Comment when user edits via permalinks updates
rspec ./spec/system/comments/user_fills_out_comment_spec.rb:13 # Creating Comment User fills out comment box normally
rspec ./spec/system/comments/user_fills_out_comment_spec.rb:20 # Creating Comment User fill out commen box then click previews and submit
rspec ./spec/system/comments/user_fills_out_comment_spec.rb:32 # Creating Comment User replies to a comment
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
