### ISSUE TITLE
Error comparing follower id's

### ISSUE THREAD

**Issue by keithrbennett** [thepracticaldev/dev.to#5157]
**Describe the bug**

When running `rails spec` I get 2 errors relating to followers in the attached file. An excerpt:

```  1) Notifications::NewFollower::Send when 2 user follows another user creates a notification with data
     Failure/Error: expect(notification.notifiable).to eq(follow2)

       expected: #<Follow id: 1078, blocked: false, created_at: "2019-12-17 09:29:54", followable_id: 13534, followabl...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-17 09:29:54">
            got: #<Follow id: 1077, blocked: false, created_at: "2019-12-17 09:29:54", followable_id: 13534, followabl...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-17 09:29:54">
...
     # ./spec/services/notifications/new_follower/send_spec.rb:95:in `block (3 levels) in <top (required)>'
```

Strangely, when I run the test individually in RubyMine, the error does not occur.

- Device: MacBook Pro
- OS: Mac OS Mojave
- Browser: N/A
- Version: N/A

Test Output File:

[spec-output.txt](https://github.com/thepracticaldev/dev.to/files/3973398/spec-output.txt)

**Comment by keithrbennett** [comment]
One of the lines that produces this errors can be seen at https://github.com/thepracticaldev/dev.to/blob/d0441bb4567e88e558514bd43c5bc28e95c191a1/spec/services/notifications/new_follower/send_spec.rb#L95.

**Comment by keithrbennett** [comment]
I had been running the tests on my Mac which had Postgres 12.1 installed. travis.yml specifies 9.6. I downgraded to 9.6 and the tests stopped failing. Very strange.

**Comment by robbkidd** [comment]
Seems to happen reliably with PostgreSQL 12 and running `rspec ./spec/services`. Failures occur when scoped to `spec/services` and do _not_ occur when scoped smaller:

💚  `rspec ./spec/services/notifications/new_follower/send_spec.rb`
💚  `rspec ./spec/services/notifications/new_follower`
💚  `rspec ./spec/services/notifications`
😭   `rspec ./spec/services`

## Showing the Work

### Run the test suite against PG versions 9 through 12.

```
» export DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/
for pg_ver in $(seq 9 12); do

  echo "\n-={ Testing with PostgreSQL ${pg_ver}! }=-\n"
  export POSTGRES_VERSION=$pg_ver

  docker-compose up --detach db redis

  sleep 10

  rake db:test:prepare > /dev/null
  rspec ./spec/services/

  docker-compose down
done
```

... produces ...

<details><summary>-={ Testing with PostgreSQL 9! }=-</summary>

```
Creating network "devto_default" with the default driver
Creating devto_redis_1 ... done
Creating devto_db_1    ... done
........................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 1 minute 8.8 seconds (files took 6.18 seconds to load)
392 examples, 0 failures

Coverage report generated for RSpec to /Users/rkidd/code/dev.to/coverage. 4587 / 12766 LOC (35.93%) covered.
Stopping devto_redis_1 ... done
Stopping devto_db_1    ... done
Removing devto_redis_1 ... done
Removing devto_db_1    ... done
Removing network devto_default
```

</details>
<details><summary>-={ Testing with PostgreSQL 10! }=-</summary>

```
Creating network "devto_default" with the default driver
Creating devto_redis_1 ... done
Creating devto_db_1    ... done
........................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 1 minute 8.3 seconds (files took 6.29 seconds to load)
392 examples, 0 failures

Coverage report generated for RSpec to /Users/rkidd/code/dev.to/coverage. 4587 / 12766 LOC (35.93%) covered.
Stopping devto_redis_1 ... done
Stopping devto_db_1    ... done
Removing devto_redis_1 ... done
Removing devto_db_1    ... done
Removing network devto_default
```

</details>
<details><summary>-={ Testing with PostgreSQL 11! }=-</summary>

```
Creating network "devto_default" with the default driver
Creating devto_db_1    ... done
Creating devto_redis_1 ... done
........................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 1 minute 8.17 seconds (files took 6.34 seconds to load)
392 examples, 0 failures

Coverage report generated for RSpec to /Users/rkidd/code/dev.to/coverage. 4587 / 12766 LOC (35.93%) covered.
Stopping devto_redis_1 ... done
Stopping devto_db_1    ... done
Removing devto_redis_1 ... done
Removing devto_db_1    ... done
Removing network devto_default
```

</details>
<details><summary>-={ Testing with PostgreSQL 12! }=-</summary>

```
Creating network "devto_default" with the default driver
Creating devto_redis_1 ... done
Creating devto_db_1    ... done
...............................................................................................................................................................................................F..F.....................................................................................................................................................................................................

Failures:

  1) Notifications::NewFollower::Send when 2 user follows another user creates a notification with data
     Failure/Error: expect(notification.notifiable).to eq(follow2)

       expected: #<Follow id: 16, blocked: false, created_at: "2019-12-19 17:59:09", followable_id: 257, followable_ty...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-19 17:59:09">
            got: #<Follow id: 15, blocked: false, created_at: "2019-12-19 17:59:09", followable_id: 257, followable_ty...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-19 17:59:09">

       (compared using ==)

       Diff:

       @@ -1,10 +1,10 @@
       -#<Follow:0x00007f973c653da0
       - id: 16,
       +#<Follow:0x00007f973c7adc00
       + id: 15,
         blocked: false,
         created_at: Thu, 19 Dec 2019 21:59:09 +04 +04:00,
         followable_id: 257,
         followable_type: "User",
       - follower_id: 258,
       + follower_id: 256,
         follower_type: "User",
         points: 1.0,
         subscription_status: "all_articles",

     # ./spec/services/notifications/new_follower/send_spec.rb:95:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:90:in `block (3 levels) in <top (required)>'
     # ./.direnv/ruby/gems/vcr-5.0.0/lib/vcr.rb:264:in `turned_off'
     # ./spec/rails_helper.rb:90:in `block (2 levels) in <top (required)>'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

  2) Notifications::NewFollower::Send when 2 user follows another user when notification exists updates a notification
     Failure/Error: expect(notification.notifiable).to eq(follow2)

       expected: #<Follow id: 22, blocked: false, created_at: "2019-12-19 17:59:09", followable_id: 266, followable_ty...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-19 17:59:09">
            got: #<Follow id: 21, blocked: false, created_at: "2019-12-19 17:59:09", followable_id: 266, followable_ty...r_type: "User", points: 1.0, subscription_status: "all_articles", updated_at: "2019-12-19 17:59:09">

       (compared using ==)

       Diff:

       @@ -1,10 +1,10 @@
       -#<Follow:0x00007f96ef6c2338
       - id: 22,
       +#<Follow:0x00007f9708531988
       + id: 21,
         blocked: false,
         created_at: Thu, 19 Dec 2019 21:59:09 +04 +04:00,
         followable_id: 266,
         followable_type: "User",
       - follower_id: 267,
       + follower_id: 265,
         follower_type: "User",
         points: 1.0,
         subscription_status: "all_articles",

     # ./spec/services/notifications/new_follower/send_spec.rb:121:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:90:in `block (3 levels) in <top (required)>'
     # ./.direnv/ruby/gems/vcr-5.0.0/lib/vcr.rb:264:in `turned_off'
     # ./spec/rails_helper.rb:90:in `block (2 levels) in <top (required)>'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./.direnv/ruby/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

Finished in 1 minute 10.22 seconds (files took 6.15 seconds to load)
392 examples, 2 failures

Failed examples:

rspec ./spec/services/notifications/new_follower/send_spec.rb:93 # Notifications::NewFollower::Send when 2 user follows another user creates a notification with data
rspec ./spec/services/notifications/new_follower/send_spec.rb:119 # Notifications::NewFollower::Send when 2 user follows another user when notification exists updates a notification

Coverage report generated for RSpec to /Users/rkidd/code/dev.to/coverage. 4587 / 12766 LOC (35.93%) covered.
Stopping devto_redis_1 ... done
Stopping devto_db_1    ... done
Removing devto_redis_1 ... done
Removing devto_db_1    ... done
Removing network devto_default
```

</details>

### Bisect the failing portion of the test suite with PG 12

```
» RAILS_ENV=test rspec ./spec/services/ --seed 1234 --bisect
Bisect started using options: "./spec/services/ --seed 1234"
Running suite to find failures... (1 minute 13.01 seconds)
Starting bisect with 2 failing examples and 390 non-failing examples.
Checking that failure(s) are order-dependent... failure appears to be order-dependent

Round 1: bisecting over non-failing examples 1-390 .. ignoring examples 196-390 (25.51 seconds)
Round 2: bisecting over non-failing examples 1-195 .. ignoring examples 99-195 (25.81 seconds)
Round 3: bisecting over non-failing examples 1-98 .. ignoring examples 50-98 (25.31 seconds)
Round 4: bisecting over non-failing examples 1-49 .. ignoring examples 26-49 (20.41 seconds)
Round 5: bisecting over non-failing examples 1-25 .. ignoring examples 14-25 (16.14 seconds)
Round 6: bisecting over non-failing examples 1-13 . ignoring examples 1-7 (7.77 seconds)
Round 7: bisecting over non-failing examples 8-13 . ignoring examples 8-10 (6.37 seconds)
Round 8: bisecting over non-failing examples 11-13 .. ignoring example 13 (12.58 seconds)
Round 9: bisecting over non-failing examples 11-12 .. ignoring example 12 (12.32 seconds)
Bisect complete! Reduced necessary non-failing examples from 390 to 1 in 2 minutes 38.7 seconds.

The minimal reproduction command is:
  rspec './spec/services/audit/event/util_spec.rb[1:1:1]' './spec/services/notifications/new_follower/send_spec.rb[1:3:2,1:3:4:2]' --seed 1234
```

I'm not certain why the audit test behavior changes the expected follow and follower IDs, but this is what I could string together so far.

**Comment by maestromac** [comment]
Thanks for this report @keithrbennett and the audit @robbkidd . Wow what a weird bug indeed 🤔

**Comment by robbkidd** [comment]
#2483 👀 

Oh lord, now this has nerd-sniped me.

**Comment by keithrbennett** [comment]
Piggybacking on @robbkidd's excellent detective work, I wanted to see if I could find the specific culprit sabotaging the test when run with Postgresql 12.

My hypothesis was that something in one or more of the tests in one of the other subdirectories of spec/services was interfering, so I wrote the attached script to run tests with each subdirectory preceding new_followers, e.g.:

```
rspec -P 'spec/services/{articles,new_followers}/**/*_spec.rb'
rspec -P 'spec/services/{audit,new_followers}/**/*_spec.rb'
...etc.
```

I tested the entire spec/services directory tree before any of these and verified that the error still occurs.

The script and a couple of its output files are attached.

I was surprised to find that _none_ of the more limited test sets failed.

But also surprised that I got _another_ error on one of the tests:

```
2019-12-22_01-30-18  Testing subdir 'credits', 3 of 18.
Running command:
rake db:test:prepare > /dev/null && rspec -P 'spec/services/{credits,new_followers}/**/*_spec.rb'

Finished, exit code = pid 79131 exit 1
[Zonebie] Setting timezone: ZONEBIE_TZ="Krasnoyarsk"
.....F....

Failures:

  1) Credits::Buyer when enough credits are available updates the updated_at of the organization
     Failure/Error: expect(org.reload.updated_at.to_i >= Time.current.to_i).to be(true)

       expected true
            got false
     # ./spec/services/credits/buyer_spec.rb:55:in `block (4 levels) in <top (required)>'
     # /Users/kbennett/.rvm/gems/ruby-2.6.5/gems/timecop-0.9.1/lib/timecop/timecop.rb:201:in `travel'
     # /Users/kbennett/.rvm/gems/ruby-2.6.5/gems/timecop-0.9.1/lib/timecop/timecop.rb:129:in `send_travel'
     # /Users/kbennett/.rvm/gems/ruby-2.6.5/gems/timecop-0.9.1/lib/timecop/timecop.rb:51:in `freeze'
     # ./spec/services/credits/buyer_spec.rb:53:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:90:in `block (3 levels) in <top (required)>'
     # /Users/kbennett/.rvm/gems/ruby-2.6.5/gems/vcr-5.0.0/lib/vcr.rb:264:in `turned_off'
     # ./spec/rails_helper.rb:90:in `block (2 levels) in <top (required)>'
     ...
```

This error occurred in only one run.

Anyone have any suggestions where else to look?


[find-bad-spec.rb.txt](https://github.com/thepracticaldev/dev.to/files/3992123/find-bad-spec.rb.txt)

The file above is the Ruby script; Github did not permit uploading it with the '.rb' extension so I needed to add '.txt'. Here are some outputs of that script:

[find_bad_spec_test_2019-12-22_01-24-58.txt](https://github.com/thepracticaldev/dev.to/files/3992131/find_bad_spec_test_2019-12-22_01-24-58.txt)
[find_bad_spec_test_2019-12-22_10-35-41.txt](https://github.com/thepracticaldev/dev.to/files/3992132/find_bad_spec_test_2019-12-22_10-35-41.txt)
[find_bad_spec_test_2019-12-22_11-04-39.txt](https://github.com/thepracticaldev/dev.to/files/3992137/find_bad_spec_test_2019-12-22_11-04-39.txt)

**Comment by keithrbennett** [comment]
Maybe next I will try removing them one by one and seeing when the failure stops.

**Comment by keithrbennett** [comment]
I have posted that test script as a gist, at https://gist.github.com/keithrbennett/f71566c84d3dac7ac2181b33ef455fa3.

**Comment by keithrbennett** [comment]
I don't understand the connection between (de)serialization and the behavior we're seeing with the notifications records, but this appears to be the line that results in the error:

https://github.com/thepracticaldev/dev.to/blob/5812ecc3835ac1ca005ca5c1dde3430ed0e3d4ae/spec/services/audit/event/util_spec.rb#L9

**Comment by keithrbennett** [comment]
Sorry, @robbkidd . I did not notice before that you had already identified the offending file.

**Comment by keithrbennett** [comment]
The line in the utils.rb file causing the problem is:

```compare_to = utils.deserialize(utils.serialize(event))```

Anyone know wny?

**Comment by rhymes** [comment]
I think I know where the problem lies. Not sure yet about why it doesn't always happen but I think I know why it does:

1. recent follows order the follows by "created_at desc":

https://github.com/thepracticaldev/dev.to/blob/9638e3da2611e4116dffc009bd7b846761146776/app/services/notifications/new_follower/send.rb#L24-L25

1. then it attaches to the notification the most recent:

https://github.com/thepracticaldev/dev.to/blob/master/app/services/notifications/new_follower/send.rb#L41

1. the issue is that in this case, we have two follows that have the same exact date:

```ruby
[13] pry(#<Notifications::NewFollower::Send>)> recent_follows
=> [#<Follow:0x00007fe1c1c7d8c8
  id: 27,
  blocked: false,
  created_at: Wed, 25 Dec 2019 00:12:51 +11 +11:00,
  followable_id: 43,
  followable_type: "User",
  follower_id: 42,
  follower_type: "User",
  points: 1.0,
  subscription_status: "all_articles",
  updated_at: Wed, 25 Dec 2019 00:12:51 +11 +11:00>,
 #<Follow:0x00007fe1c1c7d648
  id: 28,
  blocked: false,
  created_at: Wed, 25 Dec 2019 00:12:51 +11 +11:00,
  followable_id: 43,
  followable_type: "User",
  follower_id: 44,
  follower_type: "User",
  points: 1.0,
  subscription_status: "all_articles",
  updated_at: Wed, 25 Dec 2019 00:12:51 +11 +11:00>]
[14] pry(#<Notifications::NewFollower::Send>)> recent_follows.map {|f| f.created_at.rfc3339 }
=> ["2019-12-25T00:12:51+11:00", "2019-12-25T00:12:51+11:00"]
```

but the one we're interested in is the one with `followable_id` `43`, which in this case happens to be the second one in the array, not the first one:

```ruby
[16] pry(#<Notifications::NewFollower::Send>)> @followable_id
=> 43
```

in a normal situation this works well because the likelyhood of two recent follows with the same creation date is next to zero.

I think the long term solution is to change https://github.com/thepracticaldev/dev.to/blob/master/app/services/notifications/new_follower/send.rb#L41 to something like:

```ruby
notification.notifiable_id = recent_follows.detect { |f| f.follower_id == @follower_id }.id
```

I did just that and I couldn't reproduce the problem anymore :)

I sent a PR here https://github.com/thepracticaldev/dev.to/pull/5236

**Comment by keithrbennett** [comment]
I was having trouble mentally parsing spec/services/notifications/new_follower/send.rb, so I tried simplifying (refactoring) it, and annotating it (see https://gist.github.com/keithrbennett/9fcb9c1beb9d54bd6b6a5e1f4a2d342b if you're interested).

I ran the specs and one of them failed:
```
  1) Notifications::NewFollower::Send when 2 user follows another user when destroyed follow and notification exists does not destroy a notification
     Failure/Error: notification.save!

     ActiveRecord::RecordInvalid:
       Validation failed: Notifiable must exist
     # ./app/services/notifications/new_follower/send.rb:55:in `call'
     # ./app/services/notifications/new_follower/send.rb:20:in `call'
     # ./spec/services/notifications/new_follower/send_spec.rb:136:in `block (5 levels) in <main>'
    ...
Failed examples:

rspec ./spec/services/notifications/new_follower/send_spec.rb:134 # Notifications::NewFollower::Send when 2 user follows another user when destroyed follow and notification exists does not destroy a notification
```
This was with the code replacement you suggested, @rhymes. I'm not sure if this is my refactoring, because the original code looks like it should have failed too. The thing is, that test _unfollows_, which results in the unfollowed Follow instance being deleted; so there seems to be no way the comparison of the deleted follow id with existing ones can work. I will try to look into this some more.

**Comment by rhymes** [comment]
@keithrbennett while trying to fix the spec I think I've also clarified the code a bit with some comments, see #5236
