### ISSUE TITLE
Not Authorized Error when Testing Admin User Banning

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5228]
Related #4884 

```  
1) Admin bans user checks that the user is warned, has a note, and privileges are removed
     Failure/Error: raise Pundit::NotAuthorizedError, "You must be logged in" unless user
     
     Pundit::NotAuthorizedError:
       You must be logged in
     
     # ./app/policies/application_policy.rb:5:in `initialize'
     # ./app/controllers/internal/application_controller.rb:12:in `authorize_admin'
     # ./spec/system/internal/admin_bans_or_warns_user_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:90:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:90:in `block (2 levels) in <top (required)>'
Finished in 7 minutes 17 seconds (files took 8.06 seconds to load)
3180 examples, 1 failure
Failed examples:
rspec ./spec/system/internal/admin_bans_or_warns_user_spec.rb:38 # Admin bans user checks that the user is warned, has a note, and privileges are removed
```

**Comment by icncsx** [comment]
@mstruve Hi! Could you clarify something for me? I noticed that the entire test suite took more than 7 minutes, so I decided to only run just the test which was failing.

I did `bundle exec rspec ./spec/system/internal/admin_bans_or_warns_user_spec.rb:41` and it seems like the test passes. Admittedly, I'm very new to Ruby/Rails, so I'm pretty sure I'm doing something wrong. At the same time, I really want to learn and help! I would really appreciate it if you could give me some advice 🙏 on how to tackle this.

**Comment by mstruve** [comment]
This is a flaky test which means that it fails intermittently. Usually flaky tests are caused by timing issues or by data issues. You have to either reproduce it or if you cant reproduce it, think creatively about what might cause it to fail.

**Comment by icncsx** [comment]
Thanks for the tip!
