### ISSUE TITLE
Flaky expiration_notifier_spec.rb

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#5381]
related https://github.com/thepracticaldev/dev.to/issues/4884
```
1) ProMemberships::ExpirationNotifier when there are expiring memberships with insufficient credits sets the expiration notification datetime
1268     Failure/Error: expect(pro_membership.reload.expiration_notification_at.to_i).to eq(Time.current.to_i)
1269     
1270       expected: 1580381580
1271            got: 1580381579
1272     
1273       (compared using ==)
1274     # ./spec/services/pro_memberships/expiration_notifier_spec.rb:32:in `block (4 levels) in <top (required)>'
1275     # ./spec/services/pro_memberships/expiration_notifier_spec.rb:30:in `block (3 levels) in <top (required)>'
1276     # ./spec/rails_helper.rb:95:in `block (3 levels) in <top (required)>'
1277     # ./spec/rails_helper.rb:95:in `block (2 levels) in <top (required)>'
```

**Comment by citizen428** [comment]
That's because of `Time.current.to_i`, every so often the second will flip during the run, e.g. I did not yet manage to reproduce this. We could rewrite it to something like this, WDYT?

```ruby
now = Time.current.to_i
expect(pro_membership.reload.expiration_notification_at.to_i).to be >= now
```

**Comment by gverger** [comment]
Yep, you can reproduce it by adding a `sleep(1)` between the call and the expectation.

You could use `Timecop.freeze` instead of `Timecop.travel`, or is there something I am missing?

**Comment by citizen428** [comment]
Yes, @gverger, `Timecop.freeze` should take care of this. Do you want to make a PR for this? Would be a great first contribution. 😃

**Comment by gverger** [comment]
Sure I'll do a PR. Stay tuned 😉
