### ISSUE TITLE
bin/update breaks at the Elasticsearch step

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#6085]
**Describe the bug**

It happens quite often (but sometimes it doesn't) so I'm not sure if the issue lies in the sequencing of steps the script does or that there should be some check before running what the ES step does

**To Reproduce**

1. ran `bin/update` after merging the following PRs:

```shell
+ 65eba740ab782a76a0186a4f18fa290fb1291d2c Document DataUpdateScripts, Add to Deploy Process, Add Development Check (#6068) [deploy]
+ b81c2e8df3028576c783dbc8b407575be19b8be7 Remove delayed_job (#6071) [deploy]
+ ef9611d745d007823aa00a1b6223f9ee1d82aca8 Create DataUpdateScript to Index all Tags (#6078) [deploy]
+ f1aca16a1eb7c85cb2aa1950ebc58e880204cace Improve Docker configuration (#6055)
+ 6a277ba10d94e719fae1ccd07761d6fecbe0222b remove rake jobs:work references from code (#6082) [deploy]
+ 76fe99b76a7c69321899c188afb34868b09ed1cd Add Broadcast seeds + generator service to set up for welcome notifications (#6080)
+ 02fc46a3e97bbc9e3864eca37ddcecb12f5f5aa7 Delete weekly-digest.yml (#6062)
```

2. got the following error:

```text
== Update Data ==
2020-02-15 10:38:35 +0100: PUT http://localhost:9200/tags_development_alias/_doc/1 [status:403, request:0.111s, query:N/A]
2020-02-15 10:38:35 +0100: > {"id":1,"name":"beginners","hotness_score":0,"supported":true,"short_summary":null,"rules_html":null}
2020-02-15 10:38:35 +0100: < {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}
2020-02-15 10:38:35 +0100: [403] {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}

== Update Elasticsearch ==
2020-02-15 10:38:43 +0100: PUT http://localhost:9200/_cluster/settings [status:200, request:0.055s, query:n/a]
2020-02-15 10:38:43 +0100: > {"persistent":{"action":{"auto_create_index":false}}}
2020-02-15 10:38:43 +0100: < {"acknowledged":true,"persistent":{"action":{"auto_create_index":"false"}},"transient":{}}
2020-02-15 10:38:43 +0100: HEAD http://localhost:9200/tags_development [status:200, request:0.008s, query:n/a]
2020-02-15 10:38:43 +0100: <
2020-02-15 10:38:43 +0100: HEAD http://localhost:9200/classified_listings_development [status:200, request:0.010s, query:n/a]
2020-02-15 10:38:43 +0100: <
2020-02-15 10:38:43 +0100: PUT http://localhost:9200/tags_development/_alias/tags_development_alias [status:403, request:0.004s, query:N/A]
2020-02-15 10:38:43 +0100: < {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}
2020-02-15 10:38:43 +0100: [403] {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}
rails aborted!
Elasticsearch::Transport::Transport::Errors::Forbidden: [403] {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-api-7.4.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/elasticsearch-api-7.4.0/lib/elasticsearch/api/actions/indices/put_alias.rb:40:in `put_alias'
/devto/app/services/search/tag.rb:29:in `add_alias'
/devto/app/services/search/cluster.rb:34:in `each'
/devto/app/services/search/cluster.rb:34:in `add_aliases'
/devto/app/services/search/cluster.rb:17:in `setup_indexes'
/devto/lib/tasks/search.rake:4:in `block (2 levels) in <main>'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/honeycomb-beeline-1.3.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/honeycomb-beeline-1.3.0/lib/honeycomb/client.rb:54:in `start_span'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/honeycomb-beeline-1.3.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<main>'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => search:setup
(See full trace by running task with --trace)

== Command ["bin/rails search:setup"] failed ==
```

**Expected behavior**

I expect `bin/update` to never throw errors.

To make it work I had to run `rails search:destroy` and then run `bin/update` again and it worked:

```text
== Update Elasticsearch ==
2020-02-15 10:44:33 +0100: PUT http://localhost:9200/_cluster/settings [status:200, request:0.031s, query:n/a]
2020-02-15 10:44:33 +0100: > {"persistent":{"action":{"auto_create_index":false}}}
2020-02-15 10:44:33 +0100: < {"acknowledged":true,"persistent":{"action":{"auto_create_index":"false"}},"transient":{}}
2020-02-15 10:44:33 +0100: HEAD http://localhost:9200/tags_development [status:404, request:0.070s, query:N/A]
2020-02-15 10:44:33 +0100: <
2020-02-15 10:44:33 +0100: [404]
2020-02-15 10:44:33 +0100: PUT http://localhost:9200/tags_development [status:200, request:0.446s, query:n/a]
2020-02-15 10:44:33 +0100: > {"settings":{"index":{"number_of_shards":1,"number_of_replicas":0}}}
2020-02-15 10:44:33 +0100: < {"acknowledged":true,"shards_acknowledged":true,"index":"tags_development"}
2020-02-15 10:44:33 +0100: HEAD http://localhost:9200/classified_listings_development [status:404, request:0.004s, query:N/A]
2020-02-15 10:44:33 +0100: <
2020-02-15 10:44:33 +0100: [404]
2020-02-15 10:44:33 +0100: PUT http://localhost:9200/classified_listings_development [status:200, request:0.228s, query:n/a]
2020-02-15 10:44:33 +0100: > {"settings":{"index":{"number_of_shards":1,"number_of_replicas":0}}}
2020-02-15 10:44:33 +0100: < {"acknowledged":true,"shards_acknowledged":true,"index":"classified_listings_development"}
2020-02-15 10:44:33 +0100: PUT http://localhost:9200/tags_development/_alias/tags_development_alias [status:200, request:0.036s, query:n/a]
2020-02-15 10:44:33 +0100: < {"acknowledged":true}
2020-02-15 10:44:33 +0100: PUT http://localhost:9200/classified_listings_development/_alias/classified_listings_development_alias [status:200, request:0.060s, query:n/a]
2020-02-15 10:44:33 +0100: < {"acknowledged":true}
2020-02-15 10:44:34 +0100: PUT http://localhost:9200/tags_development_alias/_mapping [status:200, request:0.092s, query:n/a]
2020-02-15 10:44:34 +0100: > {"dynamic":"strict","properties":{"id":{"type":"keyword"},"name":{"type":"text","fields":{"raw":{"type":"keyword"}}},"hotness_score":{"type":"integer"},"supported":{"type":"boolean"},"short_summary":{"type":"text"},"rules_html":{"type":"text"}}}
2020-02-15 10:44:34 +0100: < {"acknowledged":true}
2020-02-15 10:44:34 +0100: PUT http://localhost:9200/classified_listings_development_alias/_mapping [status:200, request:0.072s, query:n/a]
2020-02-15 10:44:34 +0100: > {"dynamic":"strict","properties":{"id":{"type":"keyword"},"author":{"dynamic":"strict","properties":{"username":{"type":"keyword"},"name":{"type":"keyword"},"profile_image_90":{"type":"keyword"}}},"body_markdown":{"type":"text"},"bumped_at":{"type":"date"},"category":{"type":"keyword"},"contact_via_connect":{"type":"boolean"},"expires_at":{"type":"date"},"location":{"type":"text","fields":{"raw":{"type":"keyword"}}},"processed_html":{"type":"keyword"},"slug":{"type":"text","fields":{"raw":{"type":"keyword"}}},"tags":{"type":"keyword"},"title":{"type":"text","fields":{"raw":{"type":"keyword"}}},"user_id":{"type":"keyword"}}}
2020-02-15 10:44:34 +0100: < {"acknowledged":true}
```

**Comment by citizen428** [comment]
Did you run low on disk space by any chance? Because if you do ES will go into a read-only mode.

**Comment by rhymes** [comment]
@citizen428 how low is low? I have 30 GB available right now and it's still broken 👀

**Comment by citizen428** [comment]
It depends, do you see any messages related to `o.e.c.r.a.DiskThresholdMonitor` in your ES logs?

**Comment by rhymes** [comment]
> It depends, do you see any messages related to o.e.c.r.a.DiskThresholdMonitor in your ES logs?

Interesting, apparently it's the only thing that's logging: 

```text
[2020-02-18T13:43:25,618][WARN ][o.e.c.r.a.DiskThresholdMonitor] [groove.local] flood stage disk watermark [95%] exceeded on [XaelNaFtQN2HsyqS7JmW5w][groove.local][/Users/rhymes/Development/elasticsearch-7.5.2/data/nodes/0] free: 12.7gb[2.6%], all indices on this node will be marked read-only
```

How do I tell ES to chill :D ?

> Also: how are you running ES? This just happened to me in Docker, but IIRC you're not using that, right?

Running `elasticsearch-oss` from the sources, see https://docs.dev.to/installation/mac/ 

I found this https://www.elastic.co/guide/en/elasticsearch/reference/7.5/disk-allocator.html - I guess I need to change one of those settings

These are my settings:

```shell
➜  elasticsearch-7.5.2 curl -s http://localhost:9200/_settings/ | jq
{
  "tags_development": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "blocks": {
          "read_only_allow_delete": "true"
        },
        "provided_name": "tags_development",
        "creation_date": "1581759873164",
        "number_of_replicas": "0",
        "uuid": "d26n4zB7QNehaYbyvzuNDg",
        "version": {
          "created": "7050299"
        }
      }
    }
  },
  "classified_listings_development": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "blocks": {
          "read_only_allow_delete": "true"
        },
        "provided_name": "classified_listings_development",
        "creation_date": "1581759873616",
        "number_of_replicas": "0",
        "uuid": "1DyGBvbUR_upL9DVMwvfeA",
        "version": {
          "created": "7050299"
        }
      }
    }
  }
}
```

**Comment by citizen428** [comment]
You can try to change the cluster config, something like

```
PUT _cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "10gb",
    "cluster.routing.allocation.disk.watermark.high": "5gb",
    "cluster.info.update.interval": "1m"
  }
}
```

**Comment by rhymes** [comment]
doesn't work :( I'll investigate later

```shell
➜  ~ cat data.json
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "10gb",
    "cluster.routing.allocation.disk.watermark.high": "5gb",
    "cluster.info.update.interval": "1m"
  }
}
➜  ~ curl -X PUT -H "Content-Type: application/json" --data @data.json http://localhost:9200/cluster/_settings/
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [cluster]","resource.type":"index_or_alias","resource.id":"cluster","index_uuid":"_na_","index":"cluster"}],"type":"index_not_found_exception","reason":"no such index [cluster]","resource.type":"index_or_alias","resource.id":"cluster","index_uuid":"_na_","index":"cluster"},"status":404}%
➜  ~ curl -X PUT -H "Content-Type: application/json" --data @data.json http://localhost:9200/_settings/
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [classified_listings_test] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [classified_listings_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [tags_test] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [classified_listings_test] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [classified_listings_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [tags_development] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];index [tags_test] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}%
```
