### ISSUE TITLE
Docker - Error when starting the Rails server

### ISSUE THREAD

**Issue by ryan3E0** [thepracticaldev/dev.to#6094]
**Describe the bug**

I am trying to get the Docker setup running, but I am running into this error. Please let me know if there is something I should be doing differently on my end. Thanks in advance!

```
/usr/src/app/config/environments/development.rb:116:in `block (2 levels) in <main>': Data update scripts need to be run before you can start the application. Please run rake data_updates:run (RuntimeError)
```

Full log:

<details>
  <summary>Click to expand...</summary>
  
```
WARNING: Skipping key "REDIS_URL". Already set in ENV.

=> Booting Puma

=> Rails 5.2.4.1 application starting in development

=> Run `rails server -h` for more startup options

/usr/src/app/config/environments/development.rb:116:in `block (2 levels) in <main>': Data update scripts need to be run before you can start the application. Please run rake data_updates:run (RuntimeError)

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:51:in `each'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'

from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'

from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'

from /usr/src/app/config/environment.rb:5:in `<main>'

from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'

from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'

from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'

from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'

from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'

from config.ru:3:in `block in <main>'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:27:in `app'

from /usr/local/bundle/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:51:in `start'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:142:in `tap'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/server/server_command.rb:142:in `perform'

from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'

from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'

from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command/base.rb:69:in `perform'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command.rb:46:in `invoke'

from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<main>'

from bin/rails:4:in `<main>'

I, [2020-02-16T20:46:42.034544 #1] INFO -- : Whitelisting 172.19.0.1 for BetterErrors and Web Console

Exiting
```
</details>

**To Reproduce**

- Clone the latest dev.to repository.
- Follow the instructions on [https://docs.dev.to/installation/docker/](https://docs.dev.to/installation/docker/).
- On the `docker-compose up` step is when this error occurs when it tries to start the Rails server.

**Expected behavior**

The necessary steps run prior to starting the Rails server. The Rails app then starts successfully.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS/Version: 
    - Windows 10
        - Version 1903, OS Build 18362.657
    - Docker
        - Docker Desktop 2.2.0.3 (42716), Engine 19.03.5, Compose 1.25.4

**Additional context**

N/A

**Comment by citizen428** [comment]
Hi @ryan3E0, thanks for your report. As the error message indicates, Please run rake data_updates:run`. To do this within our Docker Compose workflow the command is

```sh
$ docker-compose run web rails search:setup
```

I already updated the docs, but they haven't been deployed yet.

**Comment by ryan3E0** [comment]
@citizen428, that worked. I think the docs update had some typos so I submitted a PR to fix those. Thanks!

**Comment by citizen428** [comment]
Thanks for the PR @ryan3E0, much appreciated.
