### ISSUE TITLE
not able to run dev in production when providing application.yml 

### ISSUE THREAD

**Issue by atithiapp** [thepracticaldev/dev.to#622]
no i am getting this error in production
when i ran
RAILS_ENV=production bin/setup --trace

```
== Preparing database ==
rails aborted!
NoMethodError: undefined method `reject' for #<String:0x000055b6012d9cb0>
/root/dev.to/config/application.rb:14:in `<module:PracticalDeveloper>'
/root/dev.to/config/application.rb:13:in `<top (required)>'
/root/dev.to/Rakefile:4:in `require'
/root/dev.to/Rakefile:4:in `<top (required)>'
/root/dev.to/bin/rails:9:in `require'
/root/dev.to/bin/rails:9:in `<top (required)>'
/root/dev.to/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
root@forum-rizwan:~/dev.to# 
```

**Comment by pkfrank** [comment]
Hey @atithiapp please check out this [thread on DEV](https://dev.to/ben/so-you-want-to-stand-up-your-own-instance-of-dev-help-thread-1elo) for more information, considerations, and current-limitations related to standing up your own instance of DEV.  Feel free to @-mention me or @benhalpern with any questions.
