### ISSUE TITLE
database migration can not be started on gitpod

### ISSUE THREAD

**Issue by basarozcan** [thepracticaldev/dev.to#7040]
**Describe the bug**

I'm not able to finish the setup on gitpod because database migration script not working.

**To Reproduce**

1. Go to https://docs.dev.to/installation/gitpod/ page
2. Click open in gitpod
3. after finish loading gitpod, enter algolia api keys to config/application.yml
4. Save file and press any key on terminal
5. see the error stated below:

```text
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.74s.

== Copying sample files ==

== Preparing database ==
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "PracticalDeveloper_development" does not exist
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:696:in `rescue in connect'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:691:in `connect'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:90:in `connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/workspace/.rvm/gems/strong_migrations-0.6.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/command.rb:48:in `invoke'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<main>'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'

Caused by:
PG::ConnectionBad: FATAL:  database "PracticalDeveloper_development" does not exist
/workspace/.rvm/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/workspace/.rvm/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/workspace/.rvm/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:90:in `connection'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/workspace/.rvm/gems/strong_migrations-0.6.2/lib/strong_migrations/database_tasks.rb:4:in `migrate'
/workspace/.rvm/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
/workspace/.rvm/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/command.rb:48:in `invoke'
/workspace/.rvm/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<main>'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/workspace/.rvm/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/workspace/.rvm/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

== Command ["bin/rails db:migrate"] failed ==
```

**Expected behavior**

Finish executing start scripts.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@basarozcan I just tried the installation and wasn't able to reproduce it :(

![Screenshot_2020-04-02 thepracticaldev dev to - master](https://user-images.githubusercontent.com/146201/78255236-55982580-74f7-11ea-8530-c16f41c7defa.png)


Could you try again?

**Comment by basarozcan** [comment]
@rhymes there are 3 console on bottom. first 2 perfectly working. There is a problem with latest one.

Also you can see Open Ports to see 3000 and 3005 are not working.

![resim](https://user-images.githubusercontent.com/2423158/78269896-d6b0e600-7512-11ea-81d6-32a47a50dea1.png)

**Comment by citizen428** [comment]
@rhymes I see the same, Redis and Elasticsearch start just fine, but the migrations don't work:

<img width="940" alt="Screen Shot 2020-04-03 at 11 10 08" src="https://user-images.githubusercontent.com/47985/78323364-c85adc80-759b-11ea-8a33-c74ab624d80f.png">

The problem is that Gitpod sets `DATABASE_URL` in the environment, so we don't create the DB and go straight to migrations.

```ruby
ENV["DATABASE_URL"]
 #=> "postgresql://gitpod@localhost"
```

If I unset `DATABASE_URL` our defaults seem to work and I can finish `bin/setup`. I'll update `.gitpod.yml` to unset the variable.
