### ISSUE TITLE
ActiveRecord::RecordNotFound when viewing article stats

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#7933]
Related #4884 

```ruby
Failures:
  1) Viewing an article stats shows stats for pro users by clicking on the stats button
     Failure/Error: user.add_role(:pro)
     
     ActiveRecord::RecordNotFound:
       Couldn't find all Roles with 'id': (509, 511) (found 1 results, but was looking for 2). Couldn't find Role with id 509.
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_viewing_an_article_stats_shows_stats_for_pro_users_by_clicking_on_the_stats_button_356.png
     
     # ./spec/system/articles/user_visits_article_stats_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:164:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:117:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:117:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'
Finished in 14 minutes 0 seconds (files took 7.82 seconds to load)
4828 examples, 1 failure, 3 pending
Failed examples:
rspec ./spec/system/articles/user_visits_article_stats_spec.rb:7 # Viewing an article stats shows stats for pro users by clicking on the stats button
```

**Comment by vaidehijoshi** [comment]
To our amazing contributors: issues labeled type: bug are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors guide.

**Comment by snackattas** [comment]
I'll pick this one up if that's ok

**Comment by mstruve** [comment]
We replaced adding the actual role with `allow(user).to receive(:pro?).and_return(true)` which solves this issue of finding the Role itself
