### ISSUE TITLE
Project setup: Database seeding fails

### ISSUE THREAD

**Issue by gaganlokesh** [thepracticaldev/dev.to#8191]
**Describe the bug**

I was trying to setup my development environment and ran into an issue while executing `rails db:setup`. The issue appears to be in the seeding code, one of the methods is being called on a `nil` class, which is causing the seeding process to fail.

Facing the same issue on GitPod as well.

**To Reproduce**

1. Clone the project and perform initial config setup
2. Run `bin/setup`

OR

1. Drop the database by running `rails db:drop`
2. Recreate database by running `rails db:setup`

By following any of the above approaches, you should see an error message as stated below.

```
  3. Creating Tags.
  4. Creating 25 Articles.
  5. Creating 30 Comments.
  6. Creating Podcasts.
  7. Creating Broadcasts.
  8. ChatChannels already exist. Skipping.
  9. Creating HtmlVariants.
  10. Creating Badges.
rails aborted!
NoMethodError: undefined method `limit' for nil:NilClass
/workspace/Projects/open-source/dev.to/db/seeds.rb:337:in `block in <main>'
/workspace/Projects/open-source/dev.to/db/seeds.rb:17:in `create_if_none'
/workspace/Projects/open-source/dev.to/db/seeds.rb:328:in `<main>'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/railties-5.2.4.3/lib/rails/engine.rb:556:in `load_seed'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/workspace/.rvm/gems/ruby-2.7.1@dev.to/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
